; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.14"

; Modules
projects[advanced_help][version] = "1.0-beta1"
projects[ais][version] = "1.1"
projects[backup_migrate][version] = "2.2"
projects[ctools][version] = "1.0"
projects[colorbox][version] = "1.2"
projects[fontyourface][version] = "2.2"
projects[custom_search][version] = "1.9"
projects[date][version] = "2.5"
projects[devel][version] = "1.2"
projects[disqus][version] = "1.9"
projects[ds][version] = "1.5"
projects[features][version] = "1.0-rc2"
projects[flexslider][version] = "1.0-rc3"
projects[insert] = "1.1"
projects[media][version] = "1.1"
projects[styles][version] = "2.0-alpha8"
projects[imageapi][version] = "1.x-dev"
projects[imagecrop][version] = "1.0-rc3"
projects[libraries][version] = "1.0"
projects[nitro][version] = "1.0"
projects[nodesquirrel][version] = "1.0-alpha2"
projects[oauth][version] = "3.0-alpha2"
projects[pathauto][version] = "1.0"
projects[socialmedia][version] = "1.0-beta11"
projects[skinr][version] = "2.0-beta1"
projects[token][version] = "1.0-beta7"
projects[twitter][version] = "3.0-beta3"
projects[views][version] = "3.3"
projects[webform][version] = "3.18"
projects[wysiwyg][version] = "2.1"
projects[widgets][version] = "1.0-beta5"
projects[xmlsitemap][version] = "2.0-rc1"
projects[google_analytics][version] = "1.2"
projects[imce][version] = "1.5"
projects[nodequeue][version] = "2.0-beta1"
projects[addtoany][version] = "3.1"
projects[] = omega_tools


; External Libraries... 
libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://jacklmoore.com/colorbox/colorbox.zip"
;libraries[TinyMCE][download][type] = "get"
;libraries[TinyMCE][download][url] = "http://www.tinymce.com/track.php?url=http%3A%2F%2Fgithub.com%2Fdownloads%2Ftinymce%2Ftinymce%2Ftinymce_3.4.7.zip"
libraries[profiler][download][type] = "get"
libraries[profiler][download][url] = "http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta1.tar.gz"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.

projects[rubik][version] = "4.0-beta8"
projects[tao][version] = "3.0-beta4"
projects[omega][version] = "3.0"
projects[touchpro][version] = "1.3"
projects[arctica][version] = "1.3"
projects[tundra][version] = "1.3"
